name: liver_disease_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.22.1
      - fastapi<0.100
      - uvicorn<0.30
      - dagshub
      - xgboost
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn